// Script to open and close sidebar
function w3_open() {
    document.getElementById('mySidebar').style.display = 'block';
    document.getElementById('myOverlay').style.display = 'block';
}

function w3_close() {
    document.getElementById('mySidebar').style.display = 'none';
    document.getElementById('myOverlay').style.display = 'none';
}

$(document).ready(function () {
    $("#more").parent().on("click", "#more", function () {
        $("#more").text("-");
        $("#more").attr("id", "less");
    });
    $("#more").parent().on("click", "#less", function () {
        $("#less").text("+");
        $("#less").attr("id", "more");
    });

    $("#«").click(function () {
        $("#projects").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/Logotipo.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>FoundThat</h5></b></p><p><b>Discipline:</b> Project I</p><p><b>Description:</b>Realization for the field of Technologies and Web Applications, a video that helps in the dissemination of the course on Technologies and Information Systems for the Web, since it is a relatively recent course about which there is not much information yet </p><p><a href='https://github.com/joaorafaelsantos/FoundThat' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code </b></i></a><a href='https://www.youtube.com/watch?v=sC33nRWhD_Q' target='_blank'> <i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a></p><p><b>Group: </b><a href='https://github.com/joaorafaelsantos' target='_blank'>João Santos</a></p><p><b>Final grade:</b> 18/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'> <img src='img/agpuzzle.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'> <div class='w3-container w3-white'><br> <p><b><h5>English Puzzle</h5> </b></p><p><b>Discipline:</b> Graphic Animation</p><p><b>Description:</b> The website in question corresponds to a game that allows the user to understand a little more of the English language by relating the images of the animals to their respective names, which is educational for the youngest. </p><p><a href='https://cdn.rawgit.com/acacmt/Puzzle-Ingl-s/9cab2a1b/Menu.html' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b> </i></a><a href='https://github.com/acacmt/Puzzle-Ingl-s' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Group: </b><a href='https://github.com/acacmt' target='_blank'>Ângela Tavares</a></p> <p><b>Final grade:</b> 17/20</p></div></div><div class='w3-third w3-container'><img src='img/aganim.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Intro ESMAD</h5></b></p><p><b>Discipline:</b> Graphic Animation</p><p><b>Description:</b> The website in question was made based on visual elements in order to impress and captivate users of the platform in order to impact them.</p><p><a href='https://cdn.rawgit.com/acacmt/Intro-Esmad/03593343/ESMAD.html' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/Intro-Esmad' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Group: </b><a href='https://github.com/acacmt' target='_blank'>Ângela Tavares</a></p><p><b>Final grade:</b> 17/20</p></div></div></div>")
    });

    $("#one").click(function () {
        $("#projects").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/Logotipo.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>FoundThat</h5></b></p><p><b>Discipline:</b> Project I</p><p><b>Description:</b>Realization for the field of Technologies and Web Applications, a video that helps in the dissemination of the course on Technologies and Information Systems for the Web, since it is a relatively recent course about which there is not much information yet </p><p><a href='https://github.com/joaorafaelsantos/FoundThat' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code </b></i></a><a href='https://www.youtube.com/watch?v=sC33nRWhD_Q' target='_blank'> <i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a></p><p><b>Group: </b><a href='https://github.com/joaorafaelsantos' target='_blank'>João Santos</a></p><p><b>Final grade:</b> 18/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'> <img src='img/agpuzzle.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'> <div class='w3-container w3-white'><br> <p><b><h5>English Puzzle</h5> </b></p><p><b>Discipline:</b> Graphic Animation</p><p><b>Description:</b> The website in question corresponds to a game that allows the user to understand a little more of the English language by relating the images of the animals to their respective names, which is educational for the youngest. </p><p><a href='https://cdn.rawgit.com/acacmt/Puzzle-Ingl-s/9cab2a1b/Menu.html' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b> </i></a><a href='https://github.com/acacmt/Puzzle-Ingl-s' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Group: </b><a href='https://github.com/acacmt' target='_blank'>Ângela Tavares</a></p> <p><b>Final grade:</b> 17/20</p></div></div><div class='w3-third w3-container'><img src='img/aganim.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Intro ESMAD</h5></b></p><p><b>Discipline:</b> Graphic Animation</p><p><b>Description:</b> The website in question was made based on visual elements in order to impress and captivate users of the platform in order to impact them.</p><p><a href='https://cdn.rawgit.com/acacmt/Intro-Esmad/03593343/ESMAD.html' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/Intro-Esmad' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Group: </b><a href='https://github.com/acacmt' target='_blank'>Ângela Tavares</a></p><p><b>Final grade:</b> 17/20</p></div></div></div>")
    });

    $("#two").click(function () {
        $("#projects").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/DC.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>NexTSIW Core</h5></b></p><p><b>Discipline:</b> System Analysis and Modeling</p><p><b>Description:</b>The group, consisting of three elements, had to develop the design of an information system to support the management of the Nucleus of Former Students of the Degree in TSIW (NexTSIW) in order to maintain alumni contact with the course and the school.</p><p><a href='pdf/Ams.pdf' target='_blank'><i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://github.com/joaorafaelsantos' target='_blank'> João Santos</a></p><p><b>Final grade:</b> 16/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/BD.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>WordlEvents</h5></b></p><p><b>Discipline:</b> Database</p><p><b>Description:</b> The group of three elements had to develop the design and implementation of a database to support the management of a company's events in order to correct possible gaps</p><p><a href='pdf/Bd.pdf' target='_blank'><i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://github.com/joaorafaelsantos' target='_blank'> João Santos</a></p><p><b>Final grade:</b> 17/20</p></div></div><div class='w3-third w3-container'><img src='img/Pw1.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>BiConde</h5></b></p><p><b>Discipline:</b> Web Programming I</p><p><b>Description:</b> The website in question was made based on visual elements in order to impress and captivate users of the platform in order to impact them and use the same.</p><p><a href='https://cdn.rawgit.com/acacmt/biConde/1e92b7d7/Menu.html' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/biConde' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Group: </b><a href='https://github.com/acacmt' target='_blank'>Ângela Tavares</a></p><p><b>Final grade:</b> 15/20</p></div></div>")
    });
    $("#three").click(function () {
        $("#projects").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/2.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>JAFWOOD</h5></b></p><p><b>Discipline:</b> Modeling and 3D environments</p><p><b>Description:</b>The group of three members, developed the modeling of an animation of according to the chosen theme and made a video where it was inserted using sound elements of the pre-production, ie, inspirations, concept design, storyboard, animatic and a name chosen by members of the group.</p><p><a href='https://youtu.be/4DEYLAUO3V4' target='_blank'><i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://github.com/joaorafaelsantos' target='_blank'> João Santos</a></p><p><b>Final grade:</b> 18/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/Logótipo (Isolado).png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>WordlEvents</h5></b></p><p><b>Discipline:</b> Project II</p><p><b>Description:</b> The group, consisting of three elements, had to develop the design and the implementation of a Web / Mobile application that allows managing event management in a place.</p><p><a href='https://wevents.herokuapp.com' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://github.com/joaorafaelsantos' target='_blank'> João Santos</a></p><p><b>Final grade:</b> 18/20</p></div></div><div class='w3-third w3-container'><img src='img/Snooker.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Snooker</h5></b></p><p><b>Discipline:</b> Graphic Systems</p><p><b>Description:</b> The group, consisting of three elements, had to develop a website through a mini-game. </p><p><a href='https://cdn.rawgit.com/FranciscoMoreira32/snooker3D/46d122a3/snooker/menuprincipal.html' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/FranciscoMoreira32/snooker3D' target='_blank'><i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://www.facebook.com/jgiesteira' target='_blank'> João Giesteira</a></p><p><b>Final grade:</b> 15/20</p></div></div>")
    });
    $("#»").click(function () {
        $("#projects").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/2.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>JAFWOOD</h5></b></p><p><b>Discipline:</b> Modeling and 3D environments</p><p><b>Description:</b>The group of three members, developed the modeling of an animation of according to the chosen theme and made a video where it was inserted using sound elements of the pre-production, ie, inspirations, concept design, storyboard, animatic and a name chosen by members of the group.</p><p><a href='https://youtu.be/4DEYLAUO3V4' target='_blank'><i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://github.com/joaorafaelsantos' target='_blank'> João Santos</a></p><p><b>Final grade:</b> 18/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/Logótipo (Isolado).png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>WordlEvents</h5></b></p><p><b>Discipline:</b> Project II</p><p><b>Description:</b> The group, consisting of three elements, had to develop the design and the implementation of a Web / Mobile application that allows managing event management in a place.</p><p><a href='https://wevents.herokuapp.com' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://github.com/joaorafaelsantos' target='_blank'> João Santos</a></p><p><b>Final grade:</b> 18/20</p></div></div><div class='w3-third w3-container'><img src='img/Snooker.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Snooker</h5></b></p><p><b>Discipline:</b> Graphic Systems</p><p><b>Description:</b> The group, consisting of three elements, had to develop a website through a mini-game. </p><p><a href='https://cdn.rawgit.com/FranciscoMoreira32/snooker3D/46d122a3/snooker/menuprincipal.html' target='_blank'><i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/FranciscoMoreira32/snooker3D' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Group: </b><a href='https://www.linkedin.com/in/afcgouveia/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3BlS%2BJ6rVzQQuQnvYt2bOwWw%3D%3D'target='_blank'>André Gouveia</a>,<a href='https://www.facebook.com/jgiesteira' target='_blank'> João Giesteira</a></p><p><b>Final grade:</b> 15/20</p></div></div>")
    });
});